name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: "Build (JDK-${{ matrix.java }}, ${{ matrix.os }})"
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        java: [ 25 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: 'Set up JDK'
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: ${{ matrix.java }}
      - name: 'Build with Bach'
        shell: bash
        run: java --show-version -D--project-version=0-ea+$(echo "${{ github.sha }}" | cut -c1-7) @build
