name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: "Build (JDK-${{ matrix.java }}, ${{ matrix.os }})"
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        java: [ 17 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Download JDK'
        uses: sormuras/download-jdk@v1
        with:
          feature: ${{ matrix.java }}
      - name: 'Set up JDK'
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: jdkfile
          jdkFile: ${{ env.JDK_FILE }}
      - name: 'Build with Bach'
        uses: sormuras/bach-build@v1
      - name: 'Release with JReleaser'
        uses: jreleaser/release-action@v1
        with:
          arguments: --version
